//
// Even Fibonacci numbers
// Problem 2
//
//    Each new term in the Fibonacci sequence is generated by adding
//    the previous two terms. By starting with 1 and 2, the first 10
//    terms will be:
//
//    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//    By considering the terms in the Fibonacci sequence whose values
//    do not exceed four million, find the sum of the even-valued
//    terms.
//
// by Perry A. Stoll


class Euler002 {

    public static void main(String[] args){
	long sum = 2;  //start with 2 from 1+2 for first term
	long prev = 2;
	long prevprev = 1;

	// start at result of 1+2,i.e. 3
	while(prev < 4000000) {
	    long cur = prev + prevprev;
	    System.out.println("cur fib is: " + cur);
	    if (cur % 2 == 0) {
		sum += cur;
	    }
	    prevprev = prev;
	    prev = cur;
	}
	System.out.println("Sum of fibonacci terms that are even and below 4x10^6: " + sum);
    }

}